# Generated by Django 5.2.4 on 2025-07-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XRayScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='xray_images/')),
                ('body_part', models.CharField(max_length=100)),
                ('scan_date', models.DateField()),
                ('institution', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('diagnosis', models.CharField(max_length=255)),
                ('tags', models.JSONField()),
            ],
        ),
    ]
