# Generated by Django 5.2.4 on 2025-07-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrayscan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='xray_images/'),
        ),
        migrations.AlterField(
            model_name='xrayscan',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
